///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
const String imgPath = 'assets/images';
const String iconsPath = 'assets/icons';


class AppImagePaths {

  static const String image = '$imgPath/pdf.pdf';
  static const String icon = '$iconsPath/icon.svg';
}